name: Bump and release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_action
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          default_bump: false
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.tag_action.outputs.new_tag }}
        with:
          name: ${{ steps.tag_action.outputs.new_tag }}
          tag_name: ${{ steps.tag_action.outputs.new_tag }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          token: ${{ secrets.PAT_TOKEN }}
